---
title: "Infectious Disease Schedule"
output: 
  html_document
---


| Week | Date | Module      |    Topic                                                                        | Readings                                                                                                                                                                                                                                                                                                                                                           | Assignments                                                                                              | Miscellaneous                                                                                                                                                                                                                                                                                                                                                                                           |
|:----:|:----:|-------------|---------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 01   | 03 F | Coronavirus | Introduction                                                                    |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 05 F |             | Coronavirus: article discussion                                                 |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 02   | 10 F |             | Coronavirus: investigations                                                     |                                                                                                                                                                                                                                                                                                                                                                    | [nCoV investigation](https://drive.google.com/file/d/1kugQCxfKDr-wLR1DnEAA5BB1Eda6Nu5z/view?usp=sharing) |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 12 F |             | Coronavirus: paper discussion of the 1918 flu                                   | [1918 flu pandemic](https://www.pnas.org/content/pnas/104/18/7582.full.pdf)                                                                                                                                                                                                                                                                                        |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 14 F |             | Coronavirus: investigations                                                     |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 03   | 17 F | Dynamics    | Simple epidemic models: introduction                                            |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 19 F |             | Simple epidemic models: flow diagrams                                           | [Modeling HIV](http://assets.press.princeton.edu/chapters/s8458.pdf)                                                                                                                                                                                                                                                                                               |                                                                                                          | [SIR model in R](https://drive.google.com/file/d/1naof3LYjfkeHl9kbM-hHGgNcmRsla0CN/view?usp=sharing)                                                                                                                                                                                                                                                                                                    |
|      | 21 F |             | Simple epidemic models: differential equations and models in R                  |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 04   | 24 F |             | Simple epidemic models in R, pt. II                                             | [Clim change and zoonoses](https://www.biorxiv.org/content/10.1101/2020.01.24.918755v1), [Global div of parasites](https://www.biorxiv.org/content/10.1101/815902v2)                                                                                                                                                                                               |                                                                                                          | [SIR model in R w/plots](https://drive.google.com/file/d/1iI160ruSG_2m8MeO4X9Ygu-v21TjKawh/view?usp=sharing), [Phillips HIV model](https://www.jstor.org/stable/pdf/2890152.pdf)                                                                                                                                                                                                                        |
|      | 26 F |             | Discussion: Climate change and zoonotic disease & Global diversity of parasites |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 28 F |             | Invited guest                                                                   |                                                                                                                                                                                                                                                                                                                                                                    | [Case Studies, pt. 1](CaseStudies_pt1.html)                                                              |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 05   | 02 M |             | Basic reproductive ratio                                                        |                                                                                                                                                                                                                                                                                                                                                                    | [Problem Set 1](ProblemSet1.html), [Problem Set 1 Key](ProblemSet1_key.html)                             |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 04 M |             | Host demography                                                                 |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 06 M |             | Multi-host pathogens                                                            | [Plague in small mammal communities](https://www.jstor.org/stable/pdf/25592866.pdf)                                                                                                                                                                                                                                                                                |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 06   | 09 M |             | Host heterogeneities (including flattening the curve)                           |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 11 M |             | ~~Spatial dynamics~~ COVID-19 conversations                                     | [Phocine distemper virus](https://www.jstor.org/stable/pdf/2647360.pdf)                                                                                                                                                                                                                                                                                            |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 13 M |             | ~~*Case study presentations*~~ Remote learning conversations                    |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 16 M |             | **Pandemic break**                                                              |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
|      | 23 M |             | **Scheduled break**                                                             |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 07   | 30 M |             | Spillover, common paper(s)                                                      | [The Ecology of Pathogen Spillover and Disease Emergence at the Human-Wildlife-Environment Interface](https://link.springer.com/chapter/10.1007/978-3-319-92373-4_8), or [A framework for the study of zoonotic disease emergence and its drivers: spillover of bat pathogens as a case study](https://royalsocietypublishing.org/doi/full/10.1098/rstb.2012.0228) | [Paper Discussions](PaperDiscussions.html)                                                               |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 08   | 06 A |             | Spillover, individual paper(s)                                                  |                                                                                                                                                                                                                                                                                                                                                                    | [Pandemic Interviews](PandemicInterviews.html), [Collaborative Paper](CollaborativePaper.html)           |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 09   | 13 A |             | Biodiversity and disease, common paper(s)                                       | [Biodiversity and Disease Transmission](https://link.springer.com/chapter/10.1007/978-3-319-92373-4_2)                                                                                                                                                                                                                                                             |                                                                                                          | [Lecture on diversity and disease](https://drive.google.com/file/d/1fwCiSIuD-kVOjE8sOSRMcgRoky7Milms/view?usp=sharing), [Lecture on diversity and disease with no audio :(](https://drive.google.com/file/d/1dxzjyzawMQX4P6hoXzb790r5AYn-IXtQ/view?usp=sharing), [Lecture on diversity and disease with Pink Floyd](https://drive.google.com/file/d/1fZ49kvRaFVCkIeFHt1QQh4Qpnrm3WGXU/view?usp=sharing) |
| 10   | 20 A |             | Biodiversity and disease, individual paper(s)                                   |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 11   | 27 A |             | Disease control, common paper(s)                                                | [8.1 or 8.2, and one Case study (8.3, 8.4, or 8.5)](https://drive.google.com/file/d/1sK281_4rVJ55OpbQR_kV10QUcAzGDPAX/view?usp=sharing) or [Controlling infectious disease outbreaks: Lessons from mathematical modelling](https://link.springer.com/article/10.1057/jphp.2009.13)                                                                                 |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| 12   | 04 M |             | Disease control, individual paper(s)                                            |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |
| Exam | 15 M |             |                                                                                 |                                                                                                                                                                                                                                                                                                                                                                    |                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                         |                                                                                                                                                                                                                                                           