---
title: "Syllabus"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    toc_depth: 3
    number_sections: true
---

# Course information
## Course description
In *Ecology and Evolution of Infectious Disease*, we will study microparasites and pathogens in human and non-human hosts. Three modules on disease dynamics, evolution, and ecology will cover topics such as spatial and temporal dynamics, vaccination, evolution of antibiotic resistance and virulence, coevolution and cospeciation, within host and geographic patterns of pathogen diversity, and the role of parasites in ecological communities and ecosystems. Assessments will include exams, quizzes, problem sets, and a project. Readings will mainly be from the primary literature. Concepts from calculus (e.g., derivatives) and algebra will be used throughout the course. Prerequisites: BI164, MA121, or equivalents.

## Learning outcomes
After taking this course as successful student:  
1. Will have gained an **understanding of parasitic interactions and their role in** in ecology and evolutionary biology.  
2. Will have **experience using mathematical and computational models** to understand spatial and temporal disease dyanmics.  
3. Be **equipped to critically evalute** public discourse of infectious disease agents.  
4. Will have **contributed to local public discourse on infectious disease**.

## Meetings in spacetime
MWF, 9:00—9:50 AM, in Olin 019B

## Text
No text is required for this course. All of the reading material will be provided the the professor.

## Assessment and grade assignment

| Assignments          | Each | No.   | Proportion of the course |
| :------------------- | :--: | :---: | :---------------------:  |
| Coronavirus          | 0.14 |  01   |           0.14           |
| Problem sets         | 0.10 |  02   |           0.20           |
| Case studies         | 0.10 |  02   |           0.20           |
| Final project        | 0.20 |  01   |           0.20           |
| Participation        | 0.02 |  13   |           0.26           |

- **Coronavirus**: We will decide the first day or two of class how much we'd like to concentrate on the current coronavirus outbreak.
- **Problem sets**: A couple of exercises for the disease dynamics part of the course.
- **Case studies**: In groups of 3, each student will present on a species of pathogen twice throughout the semester. Most Fridays we wil have two presentations on a case study.
- **Final project**: This will be an individual project that is individually coordinated with Chris.
- **Participation**: Participation is necessary for this course to succeed, and every week I will evaluate the quality of participation.

## Attendance
Regular attendance is necessary for you to succeed in this course.


# Professor information
## General
Dr. Christopher M. Moore  
Email: cmmoore  
Office: Olin 216  
Office phone: 207-859-5746  

## Office hours
T: 11 AM–1 PM  
R: 7–9 AM  
F: 1–3 PM at Mary Low Coffeehouse (With the exception of 28 Feb. and 13 March, where the Biology Deptartment seminar is from 1–2 in Olin 01 and Office Hours will be from 2–4 PM.)

# Course discourse
## Titles and names
Students are often curious about how to address their professors. I am comfortable with Dr. Moore, Professor Moore, or Chris. What’s most important to me is that we create a culture of mutual respect in the classroom. As a sign of respect to you I will, by default, address you by your first name. Should you have preferred way of being addressed (Mx. last name, nickname, etc.), I encourage your to communicate that to me.

## Participation
This success of the class (group) is contingent upon each student (individual) coming prepared and eager to engage with the course material and one another. Of course I will employ methods to muster enthusiasm and energy, but to be clear, this is a group effort. I ask that you do your best to come to class prepared by not only having read, but doing your best to understand to the extent that if called upon, you could recall the material from the reading in addition to stating your’s own analysis of the reading's strengths, weaknesses, and higher-level analogies (e.g., relating concepts to other areas of basic and applied science).

The quality and the quantity of participation will be taken into account. That is, I *fully* encourage you to participate, but I'd like for a somewhat uniform distribution of substantive discussion. In addition, an egalitarian approach is encouraged to better facilitate exchange of ideas. Nobody is interested in group members dominating discussion. If you are one that tends to monopolize discussion, try to engage others, as this is—at least—as important as the matter at hand and is a skill that is greatly underrated and can really boost the level of
discussion. If you are one that does not participate, *please* realize that your input is important to all of us! We are all intelligent and insightful, and engagement and input by all is how we will better understand the topic.

Overall, let’s just have fun learning, which is presumably why we are all here. Having a fun time playing ideological ping-pong (not dodge ball) with each other will only harbour growth and learning. Ecological theory can be abstract, conceptually challening, and a technical subject that lends itself greatly to creative and alternative views and approaches. In addition, ecological theory and modeling is a very applied topic, so I am certain that what we cover will touch upon each each of your scientific interests in some way.

## Academic integrity
Honesty, integrity, and personal responsibility are cornerstones of a Colby education and provide the foundation for scholarly inquiry, intellectual discourse, and an open and welcoming campus community. These values are articulated in the Colby Affirmation and are central to this course. You are expected to demonstrate academic honesty in all aspects of this course. If you are clear about course expectations, give credit to those whose work you rely on, and submit your best work, you are highly unlikely to commit an act of academic dishonesty.

Academic dishonesty includes, but is not limited to: violating clearly stated rules for taking an exam or completing homework; plagiarism (including material from sources without a citation and quotation marks around any borrowed words); claiming another’s work or a modification of another’s work as one’s own; buying or attempting to buy papers or projects for a course; fabricating information or citations; knowingly assisting others in acts of academic dishonesty; misrepresentations to faculty within the context of a course; and submitting the same work, including an essay that you wrote, in more than one course without the permission of the instructors.

Academic dishonesty is a serious offense against the college. Sanctions for academic dishonesty are assigned by an academic review board and may include failure on the assignment, failure in the course, or suspension or expulsion from the College.

## Athletic participation
While Colby College is supportive of athletic participation by its students, academics takes priority over athletics. Both NCAA and Colby rules prohibit missing class for practices. In the case of overlapping commitments between class and athletic competitions, the student must meet with the professor as soon as possible to discuss these overlaps. The student may request permission to miss class and make up the missed work; the instructor has final authority either to grant or to withhold permission.

## Sexual misconduct/Title IX statement
Colby College prohibits and will not tolerate sexual misconduct or gender-based discrimination of any kind. Colby is legally obligated to investigate sexual misconduct (including, but not limited to sexual assault and sexual harassment).

If you wish to speak confidentially about an incident of sexual misconduct, please contact Colby Counseling Services (207-859-4490) or the Director of the Gender and Sexual Diversity Program, Emily Schusterbauer (207-859-4093).

Students should be aware that faculty members are considered responsible employees; as such, if you disclose an incident of sexual misconduct to a faculty member, they have an obligation to report it to Colby’s Title IX Coordinator. “Disclosure” may include communication in-person, via email/phone/text, or through class assignments.

To learn more about sexual misconduct or report an incident, visit 
<a href="http://www.colby.edu/sexualviolence/" target="_blank">http://www.colby.edu/sexualviolence/</a>.

<!---
compiles page to pdf
pandoc index.md --latex-engine=xelatex -V geometry:margin=1in -o Misc/Syllabus.pdf
<small><a href="./Misc/Syllabus.pdf" download>Download this page as a .pdf, last updated 21 January 2019</a></small> --->