---
title: 'Lab 06: Rosenzweig-MacArthur & bifurcation plots'
output:
  html_document:
    number_sections: true
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(package = "deSolve")
library(package = "phaseR")
```

# Rosenzweig-MacArthur model
```{r}
RMM <- function(t, y, parms) {
  with(as.list(c(y, parms)), {
    prey_logistic <- r*V*(K - V)/K
    typeII <- a*V/(1 + a*h*V)
    pred_death <- m*P
    
    dV <- prey_logistic - typeII*P
    dP <- c*typeII*P - pred_death
      return(list(c(dV, dP)))
  })
}

time_seq <- seq(from = 0, to = 100, length.out = 1000)
y_init <- c(V = 1, P = 2)
parms <- c(r = 0.5,
           K = 10,
           a = 0.15,
           h = 2,
           c = 0.4,
           m = 0.01)

test_out <- ode(y = y_init, func = RMM, times = time_seq, parms = parms)

head(test_out)

plot(x = test_out[,1], y = test_out[,2], type = "l", ylim = c(0, 10))
  lines(x = test_out[,1], y = test_out[,3], col = "red")
```

# Phase plane
```{r one_phase, cache = T}
lims <- c(0, 10)

output_junk <- flowField(deriv = RMM, parameters = parms, state.names = c("V", "P"), xlim = lims, ylim = lims, add = F)
output_junk <- nullclines(deriv = RMM, parameters = parms, state.names = c("V", "P"), xlim = lims, ylim = lims, add = T)
output_junk <- trajectory(deriv = RMM, y0 = y_init, tlim = c(0, 500), parameters = parms, state.names = c("V", "P"), add = T)
```

# Phase plane, qualitative differences
```{r three_phases, cache=T}
lims <- c(0, 10)
parms_1 <- c(r = 0.5,
           K = 10,
           a = 0.15,
           h = 2,
           c = 0.4,
           m = 0.01)
parms_3 <- parms_2 <- parms_1
parms_2["m"] <- 0.11
parms_3["m"] <- 0.175

# m = 0.01
output_junk <- flowField(deriv = RMM, parameters = parms_1, state.names = c("V", "P"), xlim = lims, ylim = lims, add = F)
output_junk <- nullclines(deriv = RMM, parameters = parms_1, state.names = c("V", "P"), xlim = lims, ylim = lims, add = T)
output_junk <- trajectory(deriv = RMM, y0 = y_init, tlim = c(0, 500), parameters = parms_1, state.names = c("V", "P"), add = T)

# m = 0.11
output_junk <- flowField(deriv = RMM, parameters = parms_2, state.names = c("V", "P"), xlim = lims, ylim = lims, add = F)
output_junk <- nullclines(deriv = RMM, parameters = parms_2, state.names = c("V", "P"), xlim = lims, ylim = lims, add = T)
output_junk <- trajectory(deriv = RMM, y0 = y_init, tlim = c(0, 500), parameters = parms_2, state.names = c("V", "P"), add = T)

# m = 0.175
output_junk <- flowField(deriv = RMM, parameters = parms_3, state.names = c("V", "P"), xlim = lims, ylim = lims, add = F)
output_junk <- nullclines(deriv = RMM, parameters = parms_3, state.names = c("V", "P"), xlim = lims, ylim = lims, add = T)
output_junk <- trajectory(deriv = RMM, y0 = y_init, tlim = c(0, 500), parameters = parms_3, state.names = c("V", "P"), add = T)
```

# Bifurcation: simulation
```{r}
m_res <- r_res <- 20
m_vec <- seq(from = 0.12, to = 0.2, length.out = m_res)
r_vec <- seq(from = 0.3, to = 0.7, length.out = r_res)

parms_loop <- c(r = 0.5,
           K = 10,
           a = 0.15,
           h = 2,
           c = 0.4,
           m = 0.01)

y_init <- c("V" = 1, "P" = 2)

time_seq <- seq(from = 0, to = 200, length.out = 1000)

prey_mat <- matrix(data = NA, nrow = m_res, ncol = r_res)
pred_mat <- matrix(data = NA, nrow = m_res, ncol = r_res)

for (i in 1:m_res) {
    parms_loop["m"] <- m_vec[i]
  for (j in 1:r_res) {
    parms_loop["r"] <- r_vec[j]
    out <- ode(y = y_init, func = RMM, parms = parms_loop, times = time_seq)
    prey_mat[i, j] <- out[1000, 2]
    pred_mat[i, j] <- out[1000, 3]
  }
}
```

# Bifurcation: density plots
```{r}
par(mfrow = c(1, 2))
image(x = r_vec, y = m_vec, z = t(prey_mat))
image(x = r_vec, y = m_vec, z = t(pred_mat))
```

# Bifurcation: bifurcation plots
```{r}
prey_bin <- t(prey_mat)
pred_bin <- t(pred_mat)

prey_bin[prey_bin < 0.1] <- 0
prey_bin[prey_bin > 0.1] <- 1
pred_bin[pred_bin < 0.1] <- 0
pred_bin[pred_bin > 0.1] <- 1

par(mfrow = c(1, 2))
image(x = r_vec, y = m_vec, z = prey_bin, col = c("black", "white"))
image(x = r_vec, y = m_vec, z = pred_bin, col = c("black", "white"))

```

# Bifurcation: high res simulation (+ slight increase in parameter range)

```{r onehunnires, cache = T}
res <- 100
m_vec <- seq(from = 0.1, to = 0.2, length.out = res)
r_vec <- seq(from = 0.01, to = 1.1, length.out = res)

prey_mat <- matrix(data = NA, nrow = res, ncol = res)
pred_mat <- matrix(data = NA, nrow = res, ncol = res)

parms <- c(r = 0.5,
           K = 10,
           a = 0.15,
           h = 2,
           c = 0.4,
           m = 0.01)

n_steps <- 500
time_seq <- seq(from = 0, to = 350, length.out = n_steps)
parms_loop <- parms

for (i in 1:res) {
    parms_loop["m"] <- m_vec[i]
  for (j in 1:res) {
    parms_loop["r"] <- r_vec[j]
    out <- ode(y = y_init, func = RMM, times = time_seq, parms = parms_loop)
    prey_mat[i, j] <- out[n_steps,2]
    pred_mat[i, j] <- out[n_steps,3]
  }
}
```

# Bifurcation: high res density plots

```{r fig.dim = c(8, 4)}
par(mfrow = c(1, 2), mar = c(4.5, 4.5, 0.1, 0.1))
image(x = r_vec, y = m_vec, z = t(prey_mat), las = 1)
image(x = r_vec, y = m_vec, z = t(pred_mat), las = 1)
```

# Bifurcation: high res bifurcation plots

```{r fig.dim = c(8, 4)}
y_mat <- t(prey_mat)
d_mat <- t(pred_mat)

cutoff <- 0.01
y_mat[y_mat > cutoff] <- 1
y_mat[y_mat < cutoff] <- 0
d_mat[d_mat > cutoff] <- 1
d_mat[d_mat < cutoff] <- 0

par(mfrow = c(1, 2), mar = c(4.5, 4.5, 0.1, 0.1))
image(x = r_vec, y = m_vec, z = y_mat, las = 1)
image(x = r_vec, y = m_vec, z = d_mat, las = 1)

```













